[tools]
node = "24.13.0"
python = "latest"
rust = "latest"

# npm
"npm:@devcontainers/cli" = "latest"
"aqua:cli/cli" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:twpayne/chezmoi" = "latest"
"aqua:openai/codex" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:x-motemen/ghq" = "latest"
fzf = "latest"

